name: CI Pipeline

# Запускать workflow при push в main и при создании pull request
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error  # Падать только на errors, warnings разрешены
          output-file: hadolint-report.txt
      
      - name: Upload Hadolint report
        uses: actions/upload-artifact@v4
        if: always()  # Загружать артефакт даже если предыдущий шаг упал
        with:
          name: hadolint-report
          path: hadolint-report.txt


  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Check out repository code
        uses: actions/checkout@v4
      
      # Шаг 2: Собрать Docker образ
      - name: Build Docker image
        run: |
          docker build -t myapp:test .
          echo "Docker image built successfully!"
      
      # Шаг 3: Проверить, что контейнер запускается
      - name: Test container
        run: |
          docker run -d --name myapp-test -p 8080:8080 myapp:test

      - name: Save build log
        run: |
          echo "Build completed at $(date) > build-log.txt"
          docker images | grep myapp >> build-log.txt

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build-log.txt

      - name: Remove container
        run: |
          sleep 10
          docker stop myapp-test
          docker rm myapp-test

  # Job 3: Публикация (только для main ветки)
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
